import React from 'react';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';
import {useDocsSidebar} from '@docusaurus/plugin-content-docs/client';

// Renders the SAME tree as the left sidebar, but in the main content area, as an
// expandable "table of contents" of every project/report. It reads the live
// autogenerated sidebar, so it updates automatically when you add/remove folders
// — nothing to maintain by hand.

const norm = (href) => (href || '').replace(/\/+$/, '');

function TreeItems({items, rootHref}) {
  return (
    <ul className="report-tree">
      {items.map((item, i) => {
        if (item.type === 'category') {
          // A project (or sub-folder). Expandable; open by default so the whole
          // index is visible at a glance, but collapsible.
          return (
            <li key={i} className="report-tree__cat">
              <details open>
                <summary className="report-tree__summary">
                  {item.href ? (
                    <Link to={item.href}>{item.label}</Link>
                  ) : (
                    <span>{item.label}</span>
                  )}
                </summary>
                <TreeItems items={item.items} rootHref={rootHref} />
              </details>
            </li>
          );
        }
        if (item.type === 'link') {
          // Skip the homepage's own entry (slug '/') so it doesn't list itself.
          if (norm(item.href) === norm(rootHref)) {
            return null;
          }
          return (
            <li key={i} className="report-tree__leaf">
              <Link to={item.href}>{item.label}</Link>
            </li>
          );
        }
        return null; // ignore 'html' / 'ref' etc.
      })}
    </ul>
  );
}

export default function ReportTree() {
  const sidebar = useDocsSidebar();
  const rootHref = useBaseUrl('/');
  if (!sidebar) {
    return null;
  }
  return (
    <div className="report-tree-root">
      <TreeItems items={sidebar.items} rootHref={rootHref} />
    </div>
  );
}
