// @ts-check
// Autogenerate the sidebar from the repo folder tree. Every folder becomes a
// collapsible category (recursively, any depth); every .md becomes a page.
// You never edit this file when adding reports — just create folders + commit.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  reportsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
